# Config for stt.py
mic_energy_threshold: 61.63
mic_duration: 0.5
google_language: en-US

# Config for deepl.py
auth_key: DEEPL_APIKEY
source_lang: EN
target_lang: JA
deepl_post_url: https://api-free.deepl.com/v2/translate

# Config for tts.py
ibm_watson_url: https://api.jp-tok.text-to-speech.watson.cloud.ibm.com/instances/a48525e6-b3bf-49d7-9858-2b99372a345b
accepted_file_type: audio/mp3
voice: ja-JP_EmiV3Voice