name: Automated syntax check

on:
  push:
    branches: 
      - "**"

jobs:
  lint:
    name: Syntax check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint with flake8
        run: |
          flake8 . --count --show-source --statistics
          flake8 . --max-line-length=110
